### ISSUE TITLE
Plugin not working 

### ISSUE THREAD

**Issue by sunhort** [hassio-addons/addon-chrony#103]
# Problem/Motivation

> Plugin not sending data to cameras
## Expected behavior

> not sure

## Actual behavior

> gives error in log
Fatal error : Could not open /var/run/chrony/chronyd.pid : Permission denied

tried to uninstall/reinstall/reboot same error, having a hard time to get into container as mc/apt/other soft not available inside

**Comment by sinclairpaul** [comment]
Please post the full addon startup log

**Comment by sunhort** [comment]
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: chrony
 A local NTP (Network Time Protocol) server for cameras etc.
-----------------------------------------------------------
 Add-on version: 2.2.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (amd64 / qemux86-64)
 Home Assistant Core: 2021.11.3
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] chrony.sh: executing... 
[cont-init.d] chrony.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:18:00] INFO: Starting chronyd...
2021-11-14T11:18:00Z chronyd version 4.1 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP -SCFILTER +SIGND +ASYNCDNS +NTS +SECHASH +IPV6 -DEBUG)
2021-11-14T11:18:00Z Fatal error : Could not open /var/run/chrony/chronyd.pid : Permission denied
[14:18:01] INFO: Starting chronyd...`

**Comment by sunhort** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: chrony
 A local NTP (Network Time Protocol) server for cameras etc.
-----------------------------------------------------------
 Add-on version: 2.2.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (amd64 / qemux86-64)
 Home Assistant Core: 2021.11.3
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] chrony.sh: executing... 
[cont-init.d] chrony.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:18:00] INFO: Starting chronyd...
2021-11-14T11:18:00Z chronyd version 4.1 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP -SCFILTER +SIGND +ASYNCDNS +NTS +SECHASH +IPV6 -DEBUG)
2021-11-14T11:18:00Z Fatal error : Could not open /var/run/chrony/chronyd.pid : Permission denied
[14:18:01] INFO: Starting chronyd...
