### ISSUE TITLE
Chrony Router Configuration

### ISSUE THREAD

**Issue by ketrack** [hassio-addons/addon-chrony#117]
# Problem/Motivation

> Chrony Router Configuration

 I thought that in order to use this as my localized NTP server I would just have to set my home assistant IP as the NTP server on my router.
> (What you expected to happen)

My NTP consistently says that it is out of sync. 

> (What actually happened)

## Steps to reproduce

Set their home assistant IP as their NTP server / pool on their router.

## Proposed changes

I really appreciate your add-on however I feel lost in utilizing it as the NTP server on my router. Thank you for your help!

**Comment by sinclairpaul** [comment]
Please post addon logs and config.

I'll be honest, I don't really follow your use case, why would you point a device which has full internet access against an internally managed time source?

**Comment by ketrack** [comment]
The idea is to try and keep as much internet traffic local as possible. I got the idea from a video on the hookup YouTube channel. This way my firewall can block more unnecessary traffic. At any rate I've decided to close this issue and continue to tinker on my own.  Thank you

**Comment by sinclairpaul** [comment]
NTP sources will always be external unless you have some kind of GPS/Time source on your network, the concept of the addon is to restrict traffic for devices that do not need external access.  Without the logs from the addon, there is very little we can do to help you (I am guessing that it cannot sync externally).
