### ISSUE TITLE
Doesn't listen on secondary network interface

### ISSUE THREAD

**Issue by oleg31337** [hassio-addons/addon-chrony#122]
# Problem/Motivation
Chrony addon doesn't listen on all interfaces configured in home assistant

## Expected behavior
It needs to either listen on all available interfaces, or allow user to chose interfaces to listen on.

## Steps to reproduce

add secondary network interface in another subnet, and chrony addon only listens on primary homeassistant interface

## Proposed changes

implement option to list interfaces to listen on
OR
implement listening on all interfaces by default

**Comment by sinclairpaul** [comment]
Is multiple interfaces a supported configuration?, not sure that this is really something that effects many users.

**Comment by oleg31337** [comment]
It is more a request for improvement rather than an issue.
And yes, hass does support multiple interfaces.
Here is a good example why you would want two interfaces:
eth0 is your main network interface
eth1 is the interface  connected to surveillance subnet.

**Comment by sinclairpaul** [comment]
Thanks, sorry but this isn't something that I'm likely to spend any time on as it's such an edge use case.  You can always spin up an NTP server elsewhere, use a routed network with firewalls etc.

Thanks anyway for the suggestion.

**Comment by oleg31337** [comment]
Thanks man, I know how to do my own ntp server :-)
it was worth asking for improvement of hass component though. You can close this request without hesitation now :-D
