### ISSUE TITLE
Chrony wont start

### ISSUE THREAD

**Issue by jhalldn** [hassio-addons/addon-chrony#128]
# Problem/Motivation
Chrony wont start when click clicking start in home assistant.

## Expected behavior
Chrony should start as a addon to home assistant and provide time with ntp.

## Actual behavior
Following messages appears:

Failed to to call /addons/a0d7b954_chrony/start - Can't start addon_a0d7b954_chrony: 500 Server Error for http+docker://localhost/v1.41/containers/474c35e999870cde3b02e796bf9b44950e9feecc825adfa88960fe394ae8bf32/start: Internal Server Error ("failed to open stdout fifo: error creating fifo /var/run/docker/containerd/474c35e999870cde3b02e796bf9b44950e9feecc825adfa88960fe394ae8bf32/init-stdout: no space left on device")

## Steps to reproduce
Install, config and start (try)

## Proposed changes
Rebuild the docker image and validated before releasing

**Comment by sinclairpaul** [comment]
```"failed to open stdout fifo: error creating fifo /var/run/docker/containerd/474c35e999870cde3b02e796bf9b44950e9feecc825adfa88960fe394ae8bf32/init-stdout: no space left on device"```

Appears to be an issue on your device, this isn't anything the addon can resolve.

**Comment by jhalldn** [comment]
Not a problem with my device - all other addons are working and it no problem adding or removing addons - just this one. Is this a issue with HA?
