### ISSUE TITLE
Avoid using the `pool.ntp.org` DNS name

### ISSUE THREAD

**Issue by andrewaylett** [hassio-addons/addon-chrony#144]
# Problem/Motivation

The NTP Pool project _strongly_ prefer that people don't configure software to use `pool.ntp.org` by default: https://www.ntppool.org/en/vendors.html#open-source

## Expected behavior

That the add-on defaults to using a "vendor" pool, see https://www.ntppool.org/en/vendors.html#vendor-zone

## Actual behavior

The addon defaults to `pool.ntp.org`

## Steps to reproduce

The defaults are here: https://github.com/hassio-addons/addon-chrony/blob/main/chrony/config.yaml#L25-L26

## Proposed changes

We should acquire and use a vendor prefix supplied by the NTP Pool project.  The user experience will be the same, as the vendor prefix delegates to the pool, but we help the NTP Pool project manage the safety of the pool.

**Comment by sinclairpaul** [comment]
The addon utilises the packages in Alpine, which originally I believe are supported by Redhat.  I would suggest that the documentation/recommendation change needs to take place upstream.  From looking at the analytics there are ~3500 installs of the addon which I doubt is a major concern.
