### ISSUE TITLE
Correct GPS week rollover

### ISSUE THREAD

**Issue by RansomScientist** [hassio-addons/addon-chrony#151]
# Problem/Motivation

> Some NTP servers have become door stoppers according to their manufacturers, since they roll back nearly 20 years compared to the actual date because of their 10 bit week counter (example: https://raymarine.custhelp.com/app/answers/detail/a_id/5977/~/what-is-gps-week-number-rollover%3F-how-to-restore-incorrect-date-from-gps.#:~:text=The%20GPS%20Week%20Number%20Rollover,where%20it%20starts%20counting%20again. )
Would it be possible to correct (potentially even automatically detect and correct) this offset?

**Comment by sinclairpaul** [comment]
I don't fully understand the question, the documentation for the Chrony project (which this addon installs), can be found at <https://chrony-project.org/>
