### ISSUE TITLE
Can't install on HA 2024.7.3 ("Redirect isn't supported")

### ISSUE THREAD

**Issue by exocyt0sis** [hassio-addons/addon-chrony#169]
# Problem/Motivation

I can't install Chrony on Home Assistant 2024.7.3 running on DietPi (powered by a Raspberry Pi 4). HA is not running on Docker or in any kind of emulated environment.

## Expected behavior

Chrony should be installed on Home Assistant.

## Actual behavior

When clicking the install button, Home Assistant shows the following error message:

"This redirect isn't supported by your Home Assistant installation. It needs the Home Assistant operating system or Home Assistant Supervised. More information is available in [the documentation]."

## Steps to reproduce

Follow the installation instructions posted on https://github.com/hassio-addons/addon-chrony/blob/main/chrony/DOCS.md. Enter the IP adress of your HA server. When prompted, click the blue "Open link" button.

## Proposed changes

Please adjust the code so that Chrony can be installed on Home Asistant running on DietPi.

**Comment by sinclairpaul** [comment]
In the HA UI navigate to settings/addons, can it be installed from there?
