### ISSUE TITLE
Chrony action: Update time

### ISSUE THREAD

**Issue by DarthSonic** [hassio-addons/addon-chrony#172]
Wouldn't it be nice to be able to update/sync time by a chrony action? My issue is, system time difference is up to 1.5 seconds and when I restart chrony that is fixed. Faster would be to call a service when time is wrong.

**Comment by frenck** [comment]
> call a service

This is not an integration; I think you are mixing up concepts.

../Frenck

**Comment by DarthSonic** [comment]
Okay. Did not know that there can be no action exposed from add on.
