### ISSUE TITLE
Chrony init error

### ISSUE THREAD

**Issue by shrunbr** [hassio-addons/addon-chrony#173]
# Problem/Motivation

Chrony addon not starting.

Home Assistant Core - 2024.9.1
Home Assistant OS - 13.1

## Expected behavior

Chrony to start and run as expected.

## Actual behavior

It doesn't start.

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/f7bde9cf-3008-4000-8c45-9477f0c78fa4">

<img width="323" alt="image" src="https://github.com/user-attachments/assets/7a1def73-c834-42a9-a5ca-e93bf5c4e6f6">

## Steps to reproduce

I just installed Chrony and it doesn't start.

## Proposed changes

N/A

## Hardware Info

<img width="607" alt="image" src="https://github.com/user-attachments/assets/f34c40f8-cdcf-4046-8714-684b5e07376c">

**Comment by sinclairpaul** [comment]
Looks like it pulled the wrong image for whatever reason, you can try an "ha supervisor repair" from SSH, and also check the Supervisor logs.

It isn't an issue with the addon itself.
