### ISSUE TITLE
Use for offline enviroments

### ISSUE THREAD

**Issue by rradar** [hassio-addons/addon-chrony#18]
# Problem/Motivation

> Can't figure out how to run this addon to serve as an **ntp server** on a **raspberry pi** with **rtc** within an **offline environment**

## Expected behavior

> Grep the time from the rtc and serve it for other clients with ntp
> The rtc could get synced upstream with a gps module when needed (this logic is outside of chrony)

## Actual behavior

> Can't get it configured :bowing_man: 

## Proposed changes

> Clarify in the readme if this 'mode' is possible and how to set it up :+1:

**Comment by sinclairpaul** [comment]
At the moment you can't, the service is configured to pull NTP from a time source.  Happy to accept a PR to update the readme if you think its necessary although it does state you need a configured NTP source.  Further documentation on the service can be found at https://chrony.tuxfamily.org/faq.html

**Comment by rradar** [comment]
Thank's for the clarification.

What would happen if their is a internet time source available in the beginning for example and it will go down? Will chrony stop to serve the time via ntp when it can't sync it online or is there a fall back?

**Comment by sinclairpaul** [comment]
Full documentation can be found at https://chrony.tuxfamily.org/documentation.html which should be able to answer your questions better than I can.  The addon configures and runs the service, I would imagine however as with the majority of NTP servers, it should log an error and retry to sync.  It should always serve NTP.

**Comment by rradar** [comment]
Thank's for the link. I read a little and I think that my scenario would work (somehow)

If I interpret this one right: https://chrony.tuxfamily.org/comparison.html

Even without a rtc on a raspberry (fake hw clokc from file) this should work.

I just still don't have any clue what configuration in the hassio addon tab would make sense.

**Comment by sinclairpaul** [comment]
You can't in the addon today, the chrony.conf file would need to be changed to support it, however in all honesty I would be unlikely to change the addon to support this use case.  Of course you can always fork the addon and change it to how you would like it to behave.

**Comment by rradar** [comment]
Just one more question.

What will happen if I use the addon as intended (beeing able to get time from a upstream ntp server) and then the internet uplink fails.
Will the addon still serve time via ntp to other clients in the network or will it stop?

**Comment by sinclairpaul** [comment]
It is an NTP server, its will continue to respond.

**Comment by rradar** [comment]
But where does it take the time from if no ntp server is available? From the rtc maybe? So for my use case there must be a ntp server available once at boot and than it would just continue serving the time from rtc?

**Comment by sinclairpaul** [comment]
Won't use the RTC, it will likely require an NTP server at boot, then will work the same as any other clock....

If you need to discuss further please feel free to join the Discord server.
