### ISSUE TITLE
RTC Support for Pi I2C

### ISSUE THREAD

**Issue by macf0x** [hassio-addons/addon-chrony#21]
# Problem/Motivation

Not sure if this is even possible, but a number of vendors are making I2C RTC / GPS for the Pi and it might be something you could incorporate into the addon.

It maybe a case of Hass.io lacking the necessary kernel driver, but I thought I mention it.

Case for this is to permit standalone installs that might not have NTP access.

https://www.ebay.com.au/itm/DS3231-RTC-Precision-Clock-Memory-Module-For-Arduino-Raspberry-Pi-DIY/123807220941

https://thepihut.com/blogs/raspberry-pi-tutorials/17209332-adding-a-real-time-clock-to-your-raspberry-pi

<blockquote><img src="https://i.ebayimg.com/images/g/GzoAAOSw36tdCaGd/s-l400.jpg" width="48" align="right"><div>eBay</div><div><strong><a href="https://www.ebay.com.au/itm/DS3231-RTC-Precision-Clock-Memory-Module-For-Arduino-Raspberry-Pi-DIY-/123807220941">DS3231 RTC Precision Clock Memory Module For Arduino Raspberry Pi DIY  | eBay</a></strong></div><div>Raspberry Pi DS3231 foreign high precision clock module. The module itself can be adapted to 3.3 V and 5 V system, no level conversion, it is super convenient! Complete the clock calendar function including the second, minute.</div></blockquote>
<blockquote><img src="http://cdn.shopify.com/s/files/1/0176/3274/articles/20150218_091121_grande_5523f732-2e8f-434a-8fc1-39e719e3de71_grande.jpg?v=1540907486" width="48" align="right"><div>The Pi Hut</div><div><strong><a href="https://thepihut.com/blogs/raspberry-pi-tutorials/17209332-adding-a-real-time-clock-to-your-raspberry-pi">Adding a Real Time Clock to your Raspberry Pi</a></strong></div><div>When you switch on your PC or Mac, do you have to change its time? Highly unlikely! Do you have to on your Raspberry Pi? Possibly. Each time your Raspberry Pi boots it connects to what is called an NTP - Network Time Protocol - server and asks it the time. But what happens if your Pi is not connected to the internet? Y</div></blockquote>

**Comment by sinclairpaul** [comment]
Unfortunately I can't add this as I can't test it :)

More that happy to accept PR's.

**Comment by macf0x** [comment]
No Pi? or Module?
