### ISSUE TITLE
Hassio bad variable

### ISSUE THREAD

**Issue by quintinsleeking** [hassio-addons/addon-chrony#22]
I had the addon running smooth in Hassio. After the update i get 
> (Why the issue was filed)/init: export: line 12: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: bad variable name. 

I cannot find any help/fix for this. 

Please could someone tell me whats going on? 

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Can you post the full log please?

**Comment by quintinsleeking** [comment]
This is the whole log chrony gives me.

/init: export: line 12: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: bad variable name

**Comment by sinclairpaul** [comment]
Can you share the Supervisor Log, from Supervisor/System/System Log

**Comment by quintinsleeking** [comment]
20-02-16 15:42:31 INFO (MainThread) [hassio.addons] Create Home Assistant add-on data folder /data/addons/data/a0d7b954_chrony
20-02-16 15:42:31 INFO (SyncWorker_4) [hassio.docker.interface] Pull image hassioaddons/chrony-armv7 tag 1.0.7.
20-02-16 15:43:01 INFO (MainThread) [hassio.addons] Add-on 'a0d7b954_chrony' successfully installed
20-02-16 15:43:36 INFO (SyncWorker_19) [hassio.docker.addon] Start Docker add-on hassioaddons/chrony-armv7 with version 1.0.7

**Comment by quintinsleeking** [comment]
Thats all system log gives. Then I get the error in the Chrony log and Chrony wont start

**Comment by sinclairpaul** [comment]
It's not a particularly easy issue to troubleshoot, to confirm you just updated and the error occurred.

I assume you have attempted to remove and re add the addon?  Have you had issues with any other addons?

**Comment by quintinsleeking** [comment]
Yes have tried to remove and reinstall and then restarted with no luck. Other addons run fine

**Comment by quintinsleeking** [comment]
Just some more info. Im on HassioOS 3. 10 and Supervisor 200

**Comment by sinclairpaul** [comment]
Can you also confirm your Operating System so I can attempt to duplicate?

**Comment by quintinsleeking** [comment]
Tried few time to get chrony running. Below system logs.
20-02-16 16:05:28 INFO (SyncWorker_0) [hassio.docker.interface] Clean addon_core_configurator application
20-02-16 16:05:46 INFO (SyncWorker_0) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-configurator with version 4.2
20-02-16 16:07:21 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
20-02-16 16:09:03 INFO (SyncWorker_10) [hassio.docker.interface] Clean addon_a0d7b954_chrony application
20-02-16 16:09:43 INFO (SyncWorker_10) [hassio.docker.addon] Start Docker add-on hassioaddons/chrony-armv7 with version 1.0.7
20-02-16 16:11:02 INFO (SyncWorker_14) [hassio.docker.interface] Clean addon_a0d7b954_chrony application
20-02-16 16:11:43 INFO (SyncWorker_14) [hassio.docker.addon] Start Docker add-on hassioaddons/chrony-armv7 with version 1.0.7
20-02-16 16:12:30 INFO (SyncWorker_2) [hassio.docker.interface] Clean addon_a0d7b954_chrony application
20-02-16 16:12:55 INFO (SyncWorker_2) [hassio.docker.addon] Start Docker add-on hassioaddons/chrony-armv7 with version 1.0.7

**Comment by sinclairpaul** [comment]
Unfortunately I cannot duplicate on a Pi3 here (the addon installs and runs fine), can you please share the addon config?

Also you may wish to try running `hassio su repair` or `ha su repair` from the SSH/Web Terminal addon (depending which version you have)

**Comment by quintinsleeking** [comment]
Running the stock Chrony config. Busy running repair.

**Comment by quintinsleeking** [comment]
Just ran a repair and it fixed the problem. Thanks for the prompt response and guidance to get the problem resolved. Youre a legend.

**Comment by sinclairpaul** [comment]
Glad we got it resolved! 👍
