### ISSUE TITLE
Icon improvement

### ISSUE THREAD

**Issue by codedmind** [hassio-addons/addon-chrony#24]
# Problem/Motivation

> All the addons have color icons, and when the addon isn't running the icon is black and white, as the chrony addon icon is black and white we need to open the addon page to know if is running or stopped

## Expected behavior

> Color icon

## Actual behavior

> (What actually happened)

Icon black/white

> (How can someone else make/see it happen)

Start and stop the addon, the icon is always the same

**Comment by sinclairpaul** [comment]
Please feel free to issue a PR with an updated icon.

**Comment by martymarty004** [comment]
I'm working on the colored version of the Chrony icon and logo, I will issue a PR after I'm done so you can tell me if you like it 
(I'm not an artist, I'm just making the icon colored and adding the name of the addon in the logo)
