### ISSUE TITLE
Pool mode does not allow removing ntp_server from config

### ISSUE THREAD

**Issue by dunkelz** [hassio-addons/addon-chrony#47]
# Problem/Motivation

It is not allowed to remove ntp_server settings when mode is set to pool. When hitting Save on the config it re-populates the ntp_server option.

## Expected behavior

When **mode** is **pool** make _ntp_pool_ mandatory and allow removing _ntp_server_
When **mode** is **server** make _ntp_server_ mandatory and allow removing _ntp_pool_

## Actual behavior

When **mode** is **pool** _ntp_pool_ option cannot be removed from the config. On hitting Save it gets re-inserted.
When **mode** is **server** _ntp_server_ option cannot be removed from the config. On hitting Save it gets re-inserted.

## Steps to reproduce

See behavior

## Proposed changes

Allow removing unused configuration

**Comment by sinclairpaul** [comment]
Config validation is performed by the Home Assistant Supervisor, and currently options can either be optional or mandatory, there is no link between them.

It is cosmetic as the configuration will not be used.
