### ISSUE TITLE
Issue with time server

### ISSUE THREAD

**Issue by blakeseufert** [hassio-addons/addon-chrony#71]
# Problem/Motivation

I cannot connect devices to my Hass server with chrony. 

Running sntp 10.0.107.5 (hass ip) on my macbook returns: **sntp: Exchange failed: recv failure**

## Expected behavior
Time syncs & sntp returns timestamp.

## Actual behavior

sntp: Exchange failed: recv failure

## Steps to reproduce

Installed addon, tried to sync to it with sntp (macos terminal)

## Proposed changes

Settings are attached
![Screen Shot 2021-06-07 at 3 17 32 pm](https://user-images.githubusercontent.com/10355608/120962656-7f0bab80-c7a3-11eb-9304-0e2cf7897c9b.png)

**Comment by frenck** [comment]
Looking at your screenshot, the network port is disabled...

**Comment by blakeseufert** [comment]
Thanks, adding 123 to host field worked!
